__default__:
  name: "{rule}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 4G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{jobid}.err"
  constraint: rhel8


catR1:
  name: "catR1.{wildcards}"
catR2:
  name: "catR2.{wildcards}"
qc:
  name: "qc.{wildcards}"
trim:
  name: "trim.{wildcards}"
  memPerCpu: 5G


genoPCA:
  memPerCpu: 16G
PEER_eQTL:
  memPerCpu: 8G
PEER_nominal_eQTL:
  memPerCpu: 8G


verifybamid:
  memPerCpu: 64G
multiqc:
  memPerCpu: 8G

sig_rsIDs:
  memPerCpu: 32G
get_LDbuddy_rsIDs:
  memPerCpu: 32G
join_sigLDbuddies:
  memPerCpu: 16G
get_reQTLs:
  memPerCpu: 32G


coloc_PBS:
  memPerCpu: 32G
coloc_FNF_noresponse:
  memPerCpu: 32G
coloc_FNFresponse:
  memPerCpu: 32G


signal:
  memPerCpu: 64G
mergeAlign:
  memPerCpu: 64G
mergeSignal:
  memPerCpu: 64G
  time: 10-00:00:00
