__default__:
  name: "{rule}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 4G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{jobid}.err"
  constraint: rhel8

# RNAprocessing_1a
catR1:
  name: "catR1.{wildcards}"
catR2:
  name: "catR2.{wildcards}"
qc:
  name: "qc.{wildcards}"
trim:
  name: "trim.{wildcards}"
  memPerCpu: 5G

# eQTL_1c
verifybamid:
  memPerCpu: 64G
multiqc:
  memPerCpu: 8G

# genoCovariate_1d
genoPCA:
  memPerCpu: 16G

# QTLtools_eQTL_1e  
PEER_eQTL:
  memPerCpu: 8G
PEER_nominal_eQTL:
  memPerCpu: 8G

# conditionalQTL_top_2
get_rsIDs:
  memPerCpu: 50G
get_LDbuddies:
  memPerCpu: 32G
reformat_LDbuddies:
  memPerCpu: 32G
join_LDbuddies:
  memPerCpu: 64G



join_signal_LDbuddies:
  memPerCpu: 64G

join_sigLDbuddies:
  memPerCpu: 16G
get_reQTLs:
  memPerCpu: 32G

# RNA_signal
signal:
  memPerCpu: 64G
mergeAlign:
  memPerCpu: 64G
mergeSignal:
  memPerCpu: 64G
  time: 10-00:00:00



