__default__:
  name: "{rule}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 4G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{jobid}.err"
  constraint: rhel8


catR1:
  name: "catR1.{wildcards}"
catR2:
  name: "catR2.{wildcards}"
qc:
  name: "qc.{wildcards}"
trim:
  name: "trim.{wildcards}"
  memPerCpu: 5G


genoPCA:
  memPerCpu: 16G
PEER_eQTL:
  memPerCpu: 8G
PEER_nominal_eQTL:
  memPerCpu: 8G


verifybamid:
  memPerCpu: 64G
multiqc:
  memPerCpu: 8G

FNFsig_rsIDs:
  memPerCpu: 32G
CTLsig_rsIDs:
  memPerCpu: 32G
