## Samplesheets
samplesheet: 'samplesheet.csv' # RNA
donorSamplesheet: 'donorSamplesheet.csv' # donor information
dnaSamplesheet: 'dnaSamplesheet.csv' # DNA

# Which number of PEER factors to use
PEERfactors: 10

## Multiple testing correction type and threshold
correction: 'qval' # Which multiple testing method to filter on; 'FDR' is Benjamini-Hochberg and 'qval' is Storey Tibshirani qvalue
FDRthreshold: 0.05

## Software versions
Rversion: "4.2.2"
gatkVersion: "4.2.5.0"


## To be updated by eQTL pipeline
# Path to permutation pass eQTLs, with multiple testing correction p-value columns
eQTL_dir:
# Path to vcf inputted to QTL mapping
vcf:
# Path to normalized RNA counts
rna:
# Path to genotyping PC's
genoPC: 
genoPCkneedle:
# Covariate parameters (import same from config_QTLtools_eQTL.yaml)
RNAKitBatch:
RNASequencingBatch:
genoBatch:
DNAKitBatch: